// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkInsertLayovers implements pgx.CopyFromSource.
type iteratorForBulkInsertLayovers struct {
	rows                 []BulkInsertLayoversParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertLayovers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertLayovers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OptionID,
		r.rows[0].Duration,
		r.rows[0].Name,
		r.rows[0].AirportID,
		r.rows[0].Overnight,
	}, nil
}

func (r iteratorForBulkInsertLayovers) Err() error {
	return nil
}

func (q *Queries) BulkInsertLayovers(ctx context.Context, arg []BulkInsertLayoversParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"layover"}, []string{"option_id", "duration", "name", "airport_id", "overnight"}, &iteratorForBulkInsertLayovers{rows: arg})
}

// iteratorForBulkInsertOptions implements pgx.CopyFromSource.
type iteratorForBulkInsertOptions struct {
	rows                 []BulkInsertOptionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertOptions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertOptions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ItineraryID,
		r.rows[0].TotalDuration,
		r.rows[0].Price,
		r.rows[0].Type,
		r.rows[0].SearchedAt,
	}, nil
}

func (r iteratorForBulkInsertOptions) Err() error {
	return nil
}

func (q *Queries) BulkInsertOptions(ctx context.Context, arg []BulkInsertOptionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"options"}, []string{"itinerary_id", "total_duration", "price", "type", "searched_at"}, &iteratorForBulkInsertOptions{rows: arg})
}

// iteratorForBulkInsertSegments implements pgx.CopyFromSource.
type iteratorForBulkInsertSegments struct {
	rows                 []BulkInsertSegmentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertSegments) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertSegments) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OptionID,
		r.rows[0].DepartureAirportName,
		r.rows[0].DepartureAirportID,
		r.rows[0].DepartureTime,
		r.rows[0].ArrivalAirportName,
		r.rows[0].ArrivalAirportID,
		r.rows[0].ArrivalTime,
		r.rows[0].Duration,
		r.rows[0].Airplane,
		r.rows[0].Airline,
		r.rows[0].AirlineLogo,
		r.rows[0].TravelClass,
		r.rows[0].FlightNumber,
		r.rows[0].Overnight,
	}, nil
}

func (r iteratorForBulkInsertSegments) Err() error {
	return nil
}

func (q *Queries) BulkInsertSegments(ctx context.Context, arg []BulkInsertSegmentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"segments"}, []string{"option_id", "departure_airport_name", "departure_airport_id", "departure_time", "arrival_airport_name", "arrival_airport_id", "arrival_time", "duration", "airplane", "airline", "airline_logo", "travel_class", "flight_number", "overnight"}, &iteratorForBulkInsertSegments{rows: arg})
}
