// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Itinerary struct {
	ID              int64
	DepartureID     string
	ArrivalID       string
	Type            int32
	OutboundDate    string
	ReturnDate      pgtype.Text
	TravelClass     int32
	ShowHidden      bool
	MultiCityJson   pgtype.Text
	ExcludeBasic    bool
	DeepSearch      bool
	Adults          int32
	Children        int32
	InfantsInSeat   int32
	InfantsOnLap    int32
	SortBy          int32
	Stops           int32
	ExcludeAirlines pgtype.Text
	IncludeAirlines pgtype.Text
	Bags            int32
	MaxPrice        pgtype.Int4
	OutboundTimes   pgtype.Text
	ReturnTimes     pgtype.Text
	Emissions       pgtype.Int4
	LayoverDuration pgtype.Text
	ExcludeConns    pgtype.Text
	MaxDuration     pgtype.Int4
	Gl              string
	Hl              string
	Currency        string
	Invalid         bool
	Notify          bool
}

type Layover struct {
	ID        int64
	OptionID  int64
	Duration  int32
	Name      string
	AirportID string
	Overnight bool
}

type Option struct {
	ID            int64
	ItineraryID   int64
	TotalDuration int32
	Price         int32
	Type          string
	SearchedAt    pgtype.Timestamptz
}

type Segment struct {
	ID                   int64
	OptionID             int64
	DepartureAirportName string
	DepartureAirportID   string
	DepartureTime        string
	ArrivalAirportName   string
	ArrivalAirportID     string
	ArrivalTime          string
	Duration             int32
	Airplane             string
	Airline              string
	AirlineLogo          string
	TravelClass          string
	FlightNumber         string
	Overnight            bool
}
