// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertLayoversParams struct {
	OptionID  int64
	Duration  int32
	Name      string
	AirportID string
	Overnight bool
}

type BulkInsertOptionsParams struct {
	ItineraryID   int64
	TotalDuration int32
	Price         int32
	Type          string
	SearchedAt    pgtype.Timestamptz
}

type BulkInsertSegmentsParams struct {
	OptionID             int64
	DepartureAirportName string
	DepartureAirportID   string
	DepartureTime        string
	ArrivalAirportName   string
	ArrivalAirportID     string
	ArrivalTime          string
	Duration             int32
	Airplane             string
	Airline              string
	AirlineLogo          string
	TravelClass          string
	FlightNumber         string
	Overnight            bool
}

const createItinerary = `-- name: CreateItinerary :one
INSERT INTO itineraries (
    departure_id, arrival_id, type, outbound_date, return_date, travel_class,
    show_hidden, multi_city_json, exclude_basic, deep_search,
    adults, children, infants_in_seat, infants_on_lap,
    sort_by, stops, exclude_airlines, include_airlines, bags, max_price,
    outbound_times, return_times, emissions, layover_duration, exclude_conns,
    max_duration, gl, hl, currency
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25,
    $26, $27, $28, $29
)
RETURNING id
`

type CreateItineraryParams struct {
	DepartureID     string
	ArrivalID       string
	Type            int32
	OutboundDate    string
	ReturnDate      pgtype.Text
	TravelClass     int32
	ShowHidden      bool
	MultiCityJson   pgtype.Text
	ExcludeBasic    bool
	DeepSearch      bool
	Adults          int32
	Children        int32
	InfantsInSeat   int32
	InfantsOnLap    int32
	SortBy          int32
	Stops           int32
	ExcludeAirlines pgtype.Text
	IncludeAirlines pgtype.Text
	Bags            int32
	MaxPrice        pgtype.Int4
	OutboundTimes   pgtype.Text
	ReturnTimes     pgtype.Text
	Emissions       pgtype.Int4
	LayoverDuration pgtype.Text
	ExcludeConns    pgtype.Text
	MaxDuration     pgtype.Int4
	Gl              string
	Hl              string
	Currency        string
}

func (q *Queries) CreateItinerary(ctx context.Context, arg CreateItineraryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createItinerary,
		arg.DepartureID,
		arg.ArrivalID,
		arg.Type,
		arg.OutboundDate,
		arg.ReturnDate,
		arg.TravelClass,
		arg.ShowHidden,
		arg.MultiCityJson,
		arg.ExcludeBasic,
		arg.DeepSearch,
		arg.Adults,
		arg.Children,
		arg.InfantsInSeat,
		arg.InfantsOnLap,
		arg.SortBy,
		arg.Stops,
		arg.ExcludeAirlines,
		arg.IncludeAirlines,
		arg.Bags,
		arg.MaxPrice,
		arg.OutboundTimes,
		arg.ReturnTimes,
		arg.Emissions,
		arg.LayoverDuration,
		arg.ExcludeConns,
		arg.MaxDuration,
		arg.Gl,
		arg.Hl,
		arg.Currency,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOption = `-- name: CreateOption :one
INSERT INTO options (itinerary_id, total_duration, price, type, searched_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateOptionParams struct {
	ItineraryID   int64
	TotalDuration int32
	Price         int32
	Type          string
	SearchedAt    pgtype.Timestamptz
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOption,
		arg.ItineraryID,
		arg.TotalDuration,
		arg.Price,
		arg.Type,
		arg.SearchedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getItineraries = `-- name: GetItineraries :many
SELECT id, departure_id, arrival_id, type, outbound_date, return_date, travel_class, show_hidden, multi_city_json, exclude_basic, deep_search, adults, children, infants_in_seat, infants_on_lap, sort_by, stops, exclude_airlines, include_airlines, bags, max_price, outbound_times, return_times, emissions, layover_duration, exclude_conns, max_duration, gl, hl, currency, invalid FROM itineraries
`

func (q *Queries) GetItineraries(ctx context.Context) ([]Itinerary, error) {
	rows, err := q.db.Query(ctx, getItineraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Itinerary
	for rows.Next() {
		var i Itinerary
		if err := rows.Scan(
			&i.ID,
			&i.DepartureID,
			&i.ArrivalID,
			&i.Type,
			&i.OutboundDate,
			&i.ReturnDate,
			&i.TravelClass,
			&i.ShowHidden,
			&i.MultiCityJson,
			&i.ExcludeBasic,
			&i.DeepSearch,
			&i.Adults,
			&i.Children,
			&i.InfantsInSeat,
			&i.InfantsOnLap,
			&i.SortBy,
			&i.Stops,
			&i.ExcludeAirlines,
			&i.IncludeAirlines,
			&i.Bags,
			&i.MaxPrice,
			&i.OutboundTimes,
			&i.ReturnTimes,
			&i.Emissions,
			&i.LayoverDuration,
			&i.ExcludeConns,
			&i.MaxDuration,
			&i.Gl,
			&i.Hl,
			&i.Currency,
			&i.Invalid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLayoversByOptionIDs = `-- name: GetLayoversByOptionIDs :many
SELECT id, option_id, duration, name, airport_id, overnight
FROM layover
WHERE option_id = ANY($1::bigint[])
`

func (q *Queries) GetLayoversByOptionIDs(ctx context.Context, dollar_1 []int64) ([]Layover, error) {
	rows, err := q.db.Query(ctx, getLayoversByOptionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Layover
	for rows.Next() {
		var i Layover
		if err := rows.Scan(
			&i.ID,
			&i.OptionID,
			&i.Duration,
			&i.Name,
			&i.AirportID,
			&i.Overnight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptionsSince = `-- name: GetOptionsSince :many
SELECT id, itinerary_id, total_duration, price, type, searched_at
FROM options
WHERE itinerary_id = $1 AND searched_at >= $2
ORDER BY searched_at
`

type GetOptionsSinceParams struct {
	ItineraryID int64
	SearchedAt  pgtype.Timestamptz
}

// Returns every option saved for an itinerary at or after the given timestamp,
// ordered oldest first. Used to chart the recent price history of a flight.
func (q *Queries) GetOptionsSince(ctx context.Context, arg GetOptionsSinceParams) ([]Option, error) {
	rows, err := q.db.Query(ctx, getOptionsSince, arg.ItineraryID, arg.SearchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.ItineraryID,
			&i.TotalDuration,
			&i.Price,
			&i.Type,
			&i.SearchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSegmentsByOptionIDs = `-- name: GetSegmentsByOptionIDs :many
SELECT id, option_id, departure_airport_name, departure_airport_id, departure_time, arrival_airport_name, arrival_airport_id, arrival_time, duration, airplane, airline, airline_logo, travel_class, flight_number, overnight
FROM segments
WHERE option_id = ANY($1::bigint[])
ORDER BY id
`

// Ordered by id (i.e. insertion order) so a multi-segment option's legs always
// come back in the order they were searched/saved, keeping flight signatures
// stable across searches.
func (q *Queries) GetSegmentsByOptionIDs(ctx context.Context, dollar_1 []int64) ([]Segment, error) {
	rows, err := q.db.Query(ctx, getSegmentsByOptionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Segment
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.OptionID,
			&i.DepartureAirportName,
			&i.DepartureAirportID,
			&i.DepartureTime,
			&i.ArrivalAirportName,
			&i.ArrivalAirportID,
			&i.ArrivalTime,
			&i.Duration,
			&i.Airplane,
			&i.Airline,
			&i.AirlineLogo,
			&i.TravelClass,
			&i.FlightNumber,
			&i.Overnight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invalidateItinerary = `-- name: InvalidateItinerary :exec
UPDATE itineraries SET invalid = TRUE WHERE id = $1
`

func (q *Queries) InvalidateItinerary(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, invalidateItinerary, id)
	return err
}
